name: ussd_emulator
description: "A simple USSD emulator built with Flutter."
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  provider: ^6.1.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.1
  dio: ^5.3.2
  pdf: ^3.10.4
  share_plus: ^7.2.1
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  csv: ^5.0.2
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  mockito: ^5.4.4

flutter:
  uses-material-design: true