name: ussd_emulator
description: "A simple USSD emulator built with Flutter."
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.1.0
  provider: ^6.1.1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  connectivity_plus: ^7.0.0
  dio: ^5.3.2
  pdf: ^3.10.4
  share_plus: ^12.0.0
  file_picker: ^10.3.2
  path_provider: ^2.1.1
  csv: ^6.0.0
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3
  intl: ^0.20.2
  # UI/UX Enhancement Dependencies
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  flutter_animate: ^4.2.0
  flutter_staggered_animations: ^1.1.1
  # Security Dependencies
  flutter_secure_storage: ^9.0.0
  encrypt: ^5.0.1
  crypto: ^3.0.3
  dio_certificate_pinning: ^4.1.1
  dio_smart_retry: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7
  mockito: ^5.4.4
  intl_utils: ^2.8.5

flutter:
  uses-material-design: true
  generate: true