blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/tum/ussd_emulator/wiki
    about: Check the project documentation and wiki
  - name: Discussions
    url: https://github.com/tum/ussd_emulator/discussions
    about: Ask questions and discuss ideas with the community