// Mocks generated by Mockito 5.4.6 from annotations
// in ussd_emulator/test/widget/widgets/ussd_conversation_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:ui' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:ussd_emulator/models/endpoint_config.dart' as _i7;
import 'package:ussd_emulator/models/ussd_session.dart' as _i6;
import 'package:ussd_emulator/providers/ussd_provider.dart' as _i5;
import 'package:ussd_emulator/services/analytics_service.dart' as _i4;
import 'package:ussd_emulator/services/offline_queue_service.dart' as _i3;
import 'package:ussd_emulator/services/ussd_cache_service.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUssdCacheService_0 extends _i1.SmartFake
    implements _i2.UssdCacheService {
  _FakeUssdCacheService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOfflineQueueService_1 extends _i1.SmartFake
    implements _i3.OfflineQueueService {
  _FakeOfflineQueueService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAnalyticsService_2 extends _i1.SmartFake
    implements _i4.AnalyticsService {
  _FakeAnalyticsService_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UssdProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockUssdProvider extends _i1.Mock implements _i5.UssdProvider {
  MockUssdProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isOffline =>
      (super.noSuchMethod(Invocation.getter(#isOffline), returnValue: false)
          as bool);

  @override
  bool get lastResponseFromCache =>
      (super.noSuchMethod(
            Invocation.getter(#lastResponseFromCache),
            returnValue: false,
          )
          as bool);

  @override
  int get queuedRequestCount =>
      (super.noSuchMethod(
            Invocation.getter(#queuedRequestCount),
            returnValue: 0,
          )
          as int);

  @override
  List<_i6.UssdSession> get sessionHistory =>
      (super.noSuchMethod(
            Invocation.getter(#sessionHistory),
            returnValue: <_i6.UssdSession>[],
          )
          as List<_i6.UssdSession>);

  @override
  List<_i7.EndpointConfig> get endpointConfigs =>
      (super.noSuchMethod(
            Invocation.getter(#endpointConfigs),
            returnValue: <_i7.EndpointConfig>[],
          )
          as List<_i7.EndpointConfig>);

  @override
  _i2.UssdCacheService get cacheService =>
      (super.noSuchMethod(
            Invocation.getter(#cacheService),
            returnValue: _FakeUssdCacheService_0(
              this,
              Invocation.getter(#cacheService),
            ),
          )
          as _i2.UssdCacheService);

  @override
  _i3.OfflineQueueService get queueService =>
      (super.noSuchMethod(
            Invocation.getter(#queueService),
            returnValue: _FakeOfflineQueueService_1(
              this,
              Invocation.getter(#queueService),
            ),
          )
          as _i3.OfflineQueueService);

  @override
  _i4.AnalyticsService get analyticsService =>
      (super.noSuchMethod(
            Invocation.getter(#analyticsService),
            returnValue: _FakeAnalyticsService_2(
              this,
              Invocation.getter(#analyticsService),
            ),
          )
          as _i4.AnalyticsService);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i8.Future<void> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> startSession({
    required String? phoneNumber,
    required String? serviceCode,
    String? networkCode,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startSession, [], {
              #phoneNumber: phoneNumber,
              #serviceCode: serviceCode,
              #networkCode: networkCode,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> sendUssdInput(String? input) =>
      (super.noSuchMethod(
            Invocation.method(#sendUssdInput, [input]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> endSession() =>
      (super.noSuchMethod(
            Invocation.method(#endSession, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearSessionHistory() =>
      (super.noSuchMethod(
            Invocation.method(#clearSessionHistory, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> addEndpointConfig(_i7.EndpointConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#addEndpointConfig, [config]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateEndpointConfig(
    int? index,
    _i7.EndpointConfig? config,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateEndpointConfig, [index, config]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteEndpointConfig(int? index) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEndpointConfig, [index]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setActiveEndpointConfig(_i7.EndpointConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#setActiveEndpointConfig, [config]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> testEndpointConfig(_i7.EndpointConfig? config) =>
      (super.noSuchMethod(
            Invocation.method(#testEndpointConfig, [config]),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i9.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
